---
deployment:
  tasks:
    - export DEPLOYPATH=/home/jachpa/public_html/
    - /bin/cp -R cgi-bin $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R include $DEPLOYPATH
    - /bin/cp -R pages $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH